services:
  ollama:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile.ollama
    container_name: ia-tutor_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - MODELO=llama3.2

  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ia-tutor_web
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - MODELO=llama3.2
    depends_on:
      - ollama

volumes:
  ollama_data: